### ISSUE TITLE
go get redis-memory gives error

### ISSUE THREAD

**Issue by munai-das** [go-joe/redis-memory#5]
Hi,

i get the following error

```
➜  visibility go get github.com/go-joe/redis-memory
# github.com/go-joe/redis-memory
../../../github.com/go-joe/redis-memory/memory.go:80:30: not enough arguments in call to memory.Client.cmdable.Ping
        have ()
        want (context.Context)
../../../github.com/go-joe/redis-memory/memory.go:92:25: cannot use b.hkey (type string) as type context.Context in argument to b.Client.cmdable.HSet:
        string does not implement context.Context (missing Deadline method)
../../../github.com/go-joe/redis-memory/memory.go:98:27: not enough arguments in call to b.Client.cmdable.HGet
        have (string, string)
        want (context.Context, string, string)
../../../github.com/go-joe/redis-memory/memory.go:111:29: cannot use b.hkey (type string) as type context.Context in argument to b.Client.cmdable.HDel:
        string does not implement context.Context (missing Deadline method)
../../../github.com/go-joe/redis-memory/memory.go:117:23: not enough arguments in call to b.Client.cmdable.HKeys
        have (string)
        want (context.Context, string)
```

**Comment by fgrosse** [comment]
Hey munai, looks like you are using incompatible versions of this module and `github.com/go-redis/redis`. Probably your go version is too old to detect that `github.com/go-joe/redis-memory` is specifying its dependencies as Go module?

Concretely the `go.mod` file specifies we can use at most `v6.15.5` of `github.com/go-redis/redis` where the commands do not yet use context values. You seem to use a newer version (maybe master?).

Anyway I think its a good idea to update to a more recent redis library version but in order to properly use joe modules you need to use Go >= 1.14 which has modules support :)

**Comment by fgrosse** [comment]
Yes, looks like you tried to use master or the unreleased v8 where all commands require `context.Context` as a first argument.

https://github.com/go-redis/redis/blob/master/CHANGELOG.md#v8-unreleased
